### ISSUE TITLE
Default QoS configuration not applied to statistics

### ISSUE THREAD

**Issue by aitorhh** [eProsima/Fast-DDS#4389]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

As I understand it, the default statistics QoS configuration should be applied to the statistics data writers when no other configuration is provided (https://fast-dds.docs.eprosima.com/en/v2.13.2/fastdds/statistics/dds_layer/domainParticipant.html#auto-enabling-statistics-datawriters).

Information: https://fast-dds.docs.eprosima.com/en/v2.13.2/fastdds/statistics/dds_layer/qos.html

### Current behavior

I cannot find any way to change the QoS configuration for the statistics data writers. When debugging, it is always as follows (snippet of the qos after doing a dump of the monitor database)

````json
  "publish_mode": {
    "kind": "SYNCHRONOUS_PUBLISH_MODE"
  },
  "reliability": {
    "kind": "RELIABLE_RELIABILITY_QOS",
    "max_blocking_time": {
      "nanoseconds": 100000000,
      "seconds": 0
    }
  },
````

### Steps to reproduce

In three different shells, I run the following commands:

1. `source install/setup.sh; cd ~/install/examples/cpp/HelloWorldExample/bin; ./HelloWorldExample subscriber`
2. `source install/setup.sh; cd ~/install/examples/cpp/HelloWorldExample/bin; ./HelloWorldExample publisher -i 2000`
3. `source install/setup.sh; cd ~/install/examples/cpp/HelloWorldExample/bin; ./HelloWorldExample monitor -f dump`
4. To check modes of the different topics, I use the dump from the monitor and `cat <dump-file> | jq '.datawriters[] | select(.name | contains("statistics")) | .qos | {kind, reliability, **publish_mode}'`

The examples are used from: https://github.com/eProsima/Fast-DDS-statistics-backend (v1.0.0). But I believe the error belong to this repository. 

I have also performed the test, using the `ros2 run demo_cpp_nodes talker/listener` and no changes in the QoS.

### Fast DDS version/commit

```yaml
repositories:
    foonathan_memory_vendor:
        type: git
        url: https://github.com/eProsima/foonathan_memory_vendor.git
        version: v1.3.1
    fastcdr:
        type: git
        url: https://github.com/eProsima/Fast-CDR.git
        version: v2.1.2
    fastdds:
        type: git
        url: https://github.com/eProsima/Fast-DDS.git
        version: v2.13.0
    fastdds_statistics_backend:
        type: git
        url: https://github.com/eProsima/Fast-DDS-statistics-backend.git
        version: v1.0.0
    fastddsgen:
        type: git
        url: https://github.com/eProsima/Fast-DDS-Gen.git
        version: v3.2.0
    fastddsgen/thirdparty/idl-parser:
        type: git
        url: https://github.com/eProsima/IDL-Parser.git
        version: v3.0.0
```

From https://[raw.githubusercontent.com/eProsima/Fast-DDS-statistics-backend/v1.0.0/fastdds_statistics_backend.repos](https://raw.githubusercontent.com/eProsima/Fast-DDS-statistics-backend/v1.0.0/fastdds_statistics_backend.repos)

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

I run the example in different container using the same image based on `ubuntu:22.04`.

### XML configuration file

This issue exists with the default configuration, but also when providing custom xml configurations like the one provided https://fast-dds.docs.eprosima.com/en/latest/fastdds/statistics/dds_layer/troubleshooting.html

### Relevant log output

Not that relevant, but here is the running example:

```
listener        | Message HelloWorld 47 RECEIVED
talker          | Message: HelloWorld with index: 47 SENT
talker          | Message: HelloWorld with index: 48 SENT
listener        | Message HelloWorld 48 RECEIVED
dds-statistics  |
dds-statistics  | Fast DDS Latency of HelloWorld topic: [2024-02-16 06:21:54.724, 219.453 μs]
dds-statistics  | Publication throughput of Participant Participant_pub: [2024-02-16 06:21:54.725, 11.4969 B/s]
dds-statistics  | Dumping info in file /home/ros/dumps/graph_2024-02-16_06-21-54.json
```

Note that the example works only when there is one application running. However, when I instantiate many more publishers, the monitor does not receive the statistics information. So, I hit this reported error when trying to provide the configuration mentioned https://fast-dds.docs.eprosima.com/en/latest/fastdds/statistics/dds_layer/troubleshooting.html.

The dump from the monitor: [graph_2024-02-16_06-22-09.json](https://github.com/eProsima/Fast-DDS/files/14307119/graph_2024-02-16_06-22-09.json)
