### ISSUE TITLE
RelWithDebInfo build does not copy pdb files into install folder with Visual Studio

### ISSUE THREAD

**Issue by owillebo** [eProsima/Fast-DDS#5577]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

The CMake RelWithDebInfo build target is for building a Release build with debug information. With Visual Studio debug information is stored in separate pdb files.

The build deliverables including the pdb files must be stored in to the install\XXXX\lib (XXXX is the target, i.e. fastdds,fastcdr,...).

### Current behavior

For Debug builds these pdb files are copied in to the install\XXXX\lib folder.

For RelWithDebInfo builds pdb files are generated but NOT copied in to the install\XXXX\lib folder.

### Steps to reproduce

Just build with RelWithDebInfo.

`colcon build --cmake-args " -DCMAKE_BUILD_TYPE=RelWithDebInfo" --packages-up-to fastdds`

No pdb files are generated in the install\XXXX\lib folder.

The pdb files are generated in the build\XXXX\src\cpp\RelWithDebInfo folder.

### Fast DDS version/commit

```
repositories:
    foonathan_memory_vendor:
        type: git
        url: https://github.com/eProsima/foonathan_memory_vendor.git
        version: v1.3.1
    fastcdr:
        type: git
        url: https://github.com/eProsima/Fast-CDR.git
        version: v2.2.6
    fastdds:
        type: git
        url: https://github.com/eProsima/Fast-DDS.git
        version: v3.1.1
    fastddsgen:
        type: git
        url: https://github.com/eProsima/Fast-DDS-Gen.git
        version: v4.0.3
```

### Platform/Architecture

Windows 10 Visual Studio 2019

### Transport layer

Default configuration, UDPv4 & SHM
