### ISSUE TITLE
Interface Whitelist does not restrict VLAN interfaces

### ISSUE THREAD

**Issue by Pelcz97** [eProsima/Fast-DDS#5584]
### Is there an already existing issue for this?

- [x] I have searched the existing issues

### Expected behavior

When adding an interface into the whitelist the communication shall be restricted to only that interface. The other available interfaces shall not be used.

### Current behavior

Communication is not restricted and all multiple available interfaces are used.

### Steps to reproduce

**Setup two VLANs in two devices**
Device A
```
ip link add link eth0 name eth0.100 type vlan id 100
ip link set dev eth.100 up
ip addr add 192.168.100.163/24 dev eth0.100
ip link add link eth0 name eth0.200 type vlan id 200
ip link set dev eth.200 up
ip addr add 192.168.200.163/24 dev eth0.200
```

Device B
```
ip link add link eth0 name eth0.100 type vlan id 100
ip link set dev eth.100 up
ip addr add 192.168.100.31/24 dev eth0.100
ip link add link eth0 name eth0.200 type vlan id 200
ip link set dev eth.200 up
ip addr add 192.168.200.31/24 dev eth0.200
```

**Run ROS 2 talker and Listener**
Device A
`FASTRTPS_DEFAULT_PROFILES_FILE=test.xml RMW_FASTRTPS_USE_QOS_FROM_XML=0 RMW_IMPLEMENTATION=rmw_fastrtps_cpp ros2 run demo_nodes_cpp talker`
Device B
`ros2 run demo_nodes_cpp listener`

### Fast DDS version/commit

```
eProsima/Fast-CDR:
    type: git
    url: https://github.com/eProsima/Fast-CDR.git
    version: v1.0.24
eProsima/Fast-DDS:
    type: git
    url: https://github.com/eProsima/Fast-DDS.git
    version: v2.6.9
eProsima/foonathan_memory_vendor:
    type: git
    url: https://github.com/eProsima/foonathan_memory_vendor.git
    version: v1.2.0
```

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

UDPv4

### Additional context

**OS:**
Ubuntu 22.04
**Docker Base Image:**
Ubuntu 22.04
**ROS 2:**
Humble
**Network Transport**
UDPv4

### XML configuration file

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
<!-- Schema: https://github.com/eProsima/Fast-DDS/blob/master/resources/xsd/fastRTPS_profiles.xsd -->
    <transport_descriptors>
        <transport_descriptor>
            <transport_id>UdpVLANTransport</transport_id>
            <type>UDPv4</type>
            <interfaceWhiteList>
                <address>192.168.200.31</address>
            </interfaceWhiteList>
        </transport_descriptor>
    </transport_descriptors>
    <participant profile_name="SireneDetection" is_default_profile="true">
            <domainId>0</domainId>
            <rtps>
		<useBuiltinTransports>false</useBuiltinTransports>
                <userTransports>
                    <transport_id>UdpVLANTransport</transport_id>
                </userTransports>
            </rtps>
    </participant>
</profiles>
```

### Relevant log output

```shell

```

### Network traffic capture

[interface_whitelist_network_capture.pcapng.gz](https://github.com/user-attachments/files/18486161/interface_whitelist_network_capture.pcapng.gz)

Beginning with packet no. 878 you can see the Hello World messages on the chatter topic. The packages 878 until 883 contain the same message published on the different available interfaces.
